{"name":"Пользователь получает список свободных номеров ","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Condition with alias 'Подождите пока массив будет не пустой' didn't complete within 200 milliseconds because condition with lambda expression in steps.Steps was not fulfilled.","trace":"org.awaitility.core.ConditionTimeoutException: Condition with alias 'Подождите пока массив будет не пустой' didn't complete within 200 milliseconds because condition with lambda expression in steps.Steps was not fulfilled.\n\tat org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)\n\tat org.awaitility.core.CallableCondition.await(CallableCondition.java:78)\n\tat org.awaitility.core.CallableCondition.await(CallableCondition.java:26)\n\tat org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)\n\tat org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)\n\tat steps.Steps.retry(Steps.java:117)\n\tat RestTest.checkEmptyPhone(RestTest.java:10)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.util.ArrayList.forEach(ArrayList.java:1259)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\n\tat org.testng.TestRunner.run(TestRunner.java:585)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\n\tat org.testng.TestNG.run(TestNG.java:1037)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\nCaused by: java.util.concurrent.TimeoutException\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:205)\n\tat org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)\n\tat org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)\n\tat org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)\n\t... 33 more\n"},"stage":"finished","steps":[{"name":"retry","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Condition with alias 'Подождите пока массив будет не пустой' didn't complete within 200 milliseconds because condition with lambda expression in steps.Steps was not fulfilled.","trace":"org.awaitility.core.ConditionTimeoutException: Condition with alias 'Подождите пока массив будет не пустой' didn't complete within 200 milliseconds because condition with lambda expression in steps.Steps was not fulfilled.\n\tat org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)\n\tat org.awaitility.core.CallableCondition.await(CallableCondition.java:78)\n\tat org.awaitility.core.CallableCondition.await(CallableCondition.java:26)\n\tat org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)\n\tat org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)\n\tat steps.Steps.retry(Steps.java:117)\n\tat RestTest.checkEmptyPhone(RestTest.java:10)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.util.ArrayList.forEach(ArrayList.java:1259)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\n\tat org.testng.TestRunner.run(TestRunner.java:585)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\n\tat org.testng.TestNG.run(TestNG.java:1037)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\nCaused by: java.util.concurrent.TimeoutException\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:205)\n\tat org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)\n\tat org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)\n\tat org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)\n\t... 33 more\n"},"stage":"finished","steps":[{"name":"Получение списка свободных номеров  ","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"token","value":"72eea4084ce84851be7f21291a0d1118"}],"start":1647013735274,"stop":1647013735322},{"name":"Получение списка свободных номеров  ","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"token","value":"72eea4084ce84851be7f21291a0d1118"}],"start":1647013740576,"stop":1647013740675}],"attachments":[],"parameters":[],"start":1647013735272,"stop":1647013751800}],"attachments":[],"parameters":[],"start":1647013735270,"stop":1647013751809,"uuid":"3f7b5d46-54aa-47f2-b181-1330ed5f73ad","historyId":"8fdfd0463a38810a5e27bd1667565835","fullName":"RestTest.checkEmptyPhone","labels":[{"name":"package","value":"RestTest"},{"name":"testClass","value":"RestTest"},{"name":"testMethod","value":"checkEmptyPhone"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"yota"},{"name":"subSuite","value":"RestTest"},{"name":"host","value":"akirnik"},{"name":"thread","value":"90526@akirnik.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}